### ISSUE TITLE
✨ Add transition effect when mousing over on menu

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.MegaMenu#14]
Cc: @ozairashfaqueSSW  @apforsyth @calumjs @adamcogan @jontygardner @tiagov8 @pierssinclairssw @brydeno 

To myself,
  
### Pain

Feedback from @apforsyth
> Hi Luke M,
>
> As per Adam’s request, on SSW Rules;
> 1. See the problem - the menu does a “flash” when Adam mouses over to something else  
> The problem is at 2:18 https://youtu.be/NMHnhIMnLU0?t=138
>
> 2. Have you noticed this annoying behaviour before?
>
> 3. Fix - When the user mouses over the megamenu, only show menu if mouse hovers over menu for say ½ second.
> 
> -Andrew

There is a blink when mousing over the mega menu.

### Tasks

- [ ] Add delay and smooth transition effect when mousing over
#### Update projects that use SSW.MegaMenu
 - [ ] SSW.Rules
 - [ ] SSW.People
 - [ ] SSW.Website (old)
 - [ ] SSW.Website (new)

### Screenshots

![2022-02-21 16 57 21](https://user-images.githubusercontent.com/37203901/154921464-360db234-0b17-4830-8379-a819eb03d588.gif)
**Figure: Blink when mousing over**

Thanks!
