### ISSUE TITLE
♻️ Clean project

### ISSUE THREAD

**Issue by AttackOnMorty** [SSWConsulting/SSW.MegaMenu#15]
Cc: @bradystroud @chrisschultzssw @pierssinclairssw @tkapa @adamcogan 

To myself,

### What code could be improved?

See detailed tasks below.

### Tasks

- [x] Refactor src/lib folder
   - `data` and `images` folder should be put into a new `assets` folder
   - The other folders should be put into a new `components` folder
   - Change components from the flat structure into nested structure according to the dependences
   - Add an `index.js` file to export the `menu` and `mobile-menu` components (Those 2 are all we need to export)
- [x] For JS and CSS files inside components, they should be renamed to `index.js` and `index.module.css` (For DRY and easier module importing)
- [x] Remove useless code
   - [src/lib/mobile-dropdown-item](https://github.com/SSWConsulting/SSW.MegaMenu/blob/main/src/lib/mobile-dropdown-item/mobile-dropdown-item.js) component (Not used anymore)
   - [src/App.test.js](https://github.com/SSWConsulting/SSW.MegaMenu/blob/main/src/App.test.js)
- [x] Add Github templates and labels. Refer to the rules below:
  https://www.ssw.com.au/rules/github-issue-templates
  https://www.ssw.com.au/rules/do-you-know-how-to-use-tags-for-github-issues/

### Screenshots

![image](https://user-images.githubusercontent.com/37203901/187812887-73559e96-dffb-4785-9de5-ac28847f4cfd.png)
**Figure: Current folder structure**

Thanks!
