### ISSUE TITLE
👷CI/CD - Implement automated deployments with GitHub actions

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.MegaMenu#18]
Cc: @bradystroud @tkapa @jerryluossw @adamcogan @BrookJeynes @lukecookssw 

Hi @KristenHu 
  
### Pain
Currently, we have to manually deploy to npm.

### Suggested Solution
It should automatically deploy to npm whenever there is a commit to main. Also, there should be branch protection so you must make a PR to commit to main.

### Tasks

- [x] Check that branch Protection is implemented
- [ ] Implement a manual GitHub Action to deploy to npm

### Acceptance Criteria
- [x] Branch Protection is enabled
- [ ] GitHub Action deploys to npm
- [ ] GitHub Action is manually run and allows for [Semtantic versioning](https://semver.org/) to be input e.g. select Major, Minor or Patch release

Thanks!

**Comment by bradystroud** [comment]
As per my conversation with @KristenHu @pierssinclairssw and @wicksipedia we are changing the logic for the deploy action.

1. Test out the megamenu on a dev machine by running rules locally and the megamenu on a separate local server and see if it injects correctly
2. Create a bicep file to deploy to a storage account
3. Create a GitHub Action to deploy it whenever there is a commit to main
4. Change Website, Rules and People to refer to the component
5. Delete the npm package

**Comment by KristenHu** [comment]
> cc @lukecookssw As per my conversation with @KristenHu @pierssinclairssw and @wicksipedia we are changing the logic for the deploy action.
> 
> 1. Test out the megamenu on a dev machine by running rules locally and the megamenu on a separate local server and see if it injects correctly
> 2. Create a bicep file to deploy to a storage account
> 3. Create a GitHub Action to deploy it whenever there is a commit to main
> 4. Change Website, Rules and People to refer to the component
> 5. Delete the npm package
> 6. Document installation instructions (probably in readme)

Give up this logic to deploy package - here's a video to explain the reason: https://youtu.be/OD0ag8k5EgU
