### ISSUE TITLE
♻️ Fix Imports for ESM Packages

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.MegaMenu#26]
Cc: @bradystroud @wicksipedia 

Hi @KristenHu 

### Pain

I'm trying to implement the Megamenu for our new NextJs website coming soon, but I'm getting compile errors regarding the package.

![image](https://user-images.githubusercontent.com/17246482/213610434-11177f8f-2113-4467-83e4-65d8be7ddd9c.png)
_**FIgure: Compile problems in NextJs**_

### What code could be improved?

I think that there are sections of the `index.js` that don't properly import modules, causing issues with the build.

### Tasks

- [ ] Fix the importing of ESM modules
- [ ] Update the package
- [ ] Checked by @tkapa 

Thanks!

**Comment by tkapa** [comment]
A temporary solution I found for this in SSW.Website-v3.

I needed to enable the experimental `esmExternals` propertly in the `next.config.js`

**Comment by tkapa** [comment]
I've found that the image assets for the Megamenu are not loading properly.

This ruins the UI. 

Upon inspection is appears that the `src` for each image is `[Object object]`. After chatting to @bradystroud there might be a way around it, with some tinkering. But I'll make a new issue for this.
