### ISSUE TITLE
♻️ NPM Package | Export a single component

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.MegaMenu#28]
Cc: @wicksipedia @bradystroud @BrookJeynes 

Hi @KristenHu / Myself

### Pain

Implementing the Megamenu has been a pain. When I import the package, I just want to put the appropriate tag into my code, so that I can move on.

### What code could be improved?

In order to implement the Megamenu in my project, I want to write something like:

```
	...
	<SSWMegamenu />
	...
```

Rather than needing to import a bunch of references.

### Tasks

- [ ] Update the package to export a single usable component.
- [ ] Update the README to reflect the new implementation
- [ ] Implement and host an example site (e.g. sswmegamenu.com.au) to show people what the Menu should look like when implemented. 

Thanks!
