### ISSUE TITLE
♻️ Refactor - Upgrade to New Megamenu

### ISSUE THREAD

**Issue by Harry-Ross** [SSWConsulting/SSW.MegaMenu#47]
As per https://github.com/SSWConsulting/SSW.Website/issues/1560, the mega menu is being modified to be a standalone component that can be accessed via NPM. 

```[tasklist]
### Tasks
- [ ] Move to TypeScript
- [ ] Migrate the files from the website repo to here on a v4 branch (keeping a v3 branch for old versions)
- [ ] Add Tailwind
- [ ] Change data fetching to come from Tina/Next.js API from the v3 website
```
