### ISSUE TITLE
✨ Make MegaMenu reuseable in multiple projects

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.MegaMenu#9]
Cc: @adamcogan @pierssinclairssw @christianmorfordwaitessw 

To Myself

### Pain
Currently, the SSW Megamenu has been copied and pasted into our websites. 

Investigate how we can grab the most up to date version of the MegaMenu.

### Tasks

- [x] Investigate options to get the megamenu
- [x] Replace the megamenu in 
    - [x] SSW.People
    - [x] SSW.Rules - https://github.com/SSWConsulting/SSW.Rules/issues/905
    - [x] SSW.Website - https://github.com/SSWConsulting/SSW.Website/issues/274

Thanks!
